# Flyway Configuration
spring:
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  application:
    name: auction-system
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        type:
          preferred_uuid_jdbc_type: CHAR

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/auction-system
          jwk-set-uri: http://localhost:8180/realms/auction-system/protocol/openid-connect/certs
jwt:
  auth:
    converter:
      resource-id: auction-api
      principle-attribute: preferred_username

keycloak:
  token-uri: http://localhost:8180/realms/auction-system/protocol/openid-connect/token
  client-id: auction-api
  client-secret: ${KEYCLOAK_CLIENT_SECRET:}
  admin:
    server-url: http://localhost:8180
    realm: auction-system
    client-id: auction-api
    client-secret: ${KEYCLOAK_CLIENT_SECRET}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    tags-sorter: alpha
    operations-sorter: alpha
    persist-authorization: true

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,modulith
  endpoint:
    health:
      show-details: always

cloudinary:
  cloud_name: your_cloud_name
  api_key: your_api_key
  api_secret: your_api_secret
