# Flyway Configuration
spring:
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  application:
    name: note-system
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        type:
          preferred_uuid_jdbc_type: CHAR

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI:http://localhost:8180/realms/auction-system}
          jwk-set-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI:http://localhost:8180/realms/auction-system/protocol/openid-connect/certs}
jwt:
  auth:
    converter:
      resource-id: auction-api
      principle-attribute: preferred_username

keycloak:
  token-uri: http://localhost:8180/realms/auction-system/protocol/openid-connect/token
  client-id: auction-api
  client-secret: ${KEYCLOAK_CLIENT_SECRET:}
  admin:
    server-url: http://localhost:8180
    realm: auction-system
    client-id: auction-api
    client-secret: ${KEYCLOAK_CLIENT_SECRET}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    tags-sorter: alpha
    operations-sorter: alpha
    persist-authorization: true

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,modulith
  endpoint:
    health:
      show-details: always

cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME:}
  api_key: ${CLOUDINARY_API_KEY:}
  api_secret: ${CLOUDINARY_API_SECRET:}
