# Flyway Configuration
spring:
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  application:
    name: auction-system
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        type:
          preferred_uuid_jdbc_type: CHAR

  mustache:
    check-template-location: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/auction-system
          jwk-set-uri: http://localhost:8180/realms/auction-system/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      resource-id: auction-api
      principle-attribute: preferred_username

keycloak:
  token-uri: http://localhost:8180/realms/auction-system/protocol/openid-connect/token
  client-id: auction-api
  client-secret: ${KEYCLOAK_CLIENT_SECRET:}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    tags-sorter: alpha
    operations-sorter: alpha
    persist-authorization: true

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,modulith
  endpoint:
    health:
      show-details: always

logging:
  level:
    org:
      atmosphere: warn

vaadin:
  launch-browser: true
  bun:
    enable: true